// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/store_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/AkikoAkaki/distributed-delay-queue/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockJobStore is a mock of JobStore interface.
type MockJobStore struct {
	ctrl     *gomock.Controller
	recorder *MockJobStoreMockRecorder
	isgomock struct{}
}

// MockJobStoreMockRecorder is the mock recorder for MockJobStore.
type MockJobStoreMockRecorder struct {
	mock *MockJobStore
}

// NewMockJobStore creates a new mock instance.
func NewMockJobStore(ctrl *gomock.Controller) *MockJobStore {
	mock := &MockJobStore{ctrl: ctrl}
	mock.recorder = &MockJobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobStore) EXPECT() *MockJobStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockJobStore) Add(ctx context.Context, task *proto.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockJobStoreMockRecorder) Add(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockJobStore)(nil).Add), ctx, task)
}

// GetReady mocks base method.
func (m *MockJobStore) GetReady(ctx context.Context, topic string, limit int64) ([]*proto.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReady", ctx, topic, limit)
	ret0, _ := ret[0].([]*proto.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReady indicates an expected call of GetReady.
func (mr *MockJobStoreMockRecorder) GetReady(ctx, topic, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReady", reflect.TypeOf((*MockJobStore)(nil).GetReady), ctx, topic, limit)
}

// Remove mocks base method.
func (m *MockJobStore) Remove(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockJobStoreMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockJobStore)(nil).Remove), ctx, id)
}
